spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: test
        url: jdbc:mysql://db:3306/sphdb
        username: test
    jpa:
        hibernate:
            ddl-auto: update
    main:
        allow-bean-definition-overriding: true
    rabbitmq:
        host: rabbitmq
        password: guest
        port: 5672
        username: guest